sudo: false
language: node_js
node_js:
  - 12 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - develop # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: develop
  local-dir: public
after_success:
 - git checkout master
 - git commit -m "Enter your commit message here" -a
 - git checkout gh-pages
 - git merge master
 - git commit -m "keeping up to date with master" -a
 - git push